prometheus:
# Disable components we don't need to save resources.
  alertmanager:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  kube-state-metrics:
    enabled: false

grafana:
  persistence:
    enabled: true
    size: 1Gi
  datasources:
   datasources.yaml:
     apiVersion: 1
     datasources:
     - name: Prometheus
       type: prometheus
       url: http://monitoring-prometheus-server
       access: proxy
       isDefault: true
