apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app: {{ .Release.Name }}
    service: app
spec:
  # TODO: This should be changed to clusterIP with ingress in production.
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app: {{ .Release.Name }}
    service: app